/* FJ Production catalog — product details and image filenames supplied by the owner. */
const products = [
  {id:'ice-cool',name:'Ice Cool Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'Refresh, cleanse and revive with the Ice Cool Face Wash.',image:'assets/products/IMG-20260817-WA0078.jpg'},
  {id:'aqua-glow',name:'Aqua Glow Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'A hydrating and refreshing daily face wash.',image:'assets/products/IMG-20260817-WA0064.jpg'},
  {id:'aloe-vera',name:'Aloe Vera Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'A soothing, hydrating and refreshing face wash.',image:'assets/products/IMG-20260817-WA0065.jpg'},
  {id:'cherry',name:'Cherry Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'Fresh, gentle and radiant daily cleansing.',image:'assets/products/IMG-20260817-WA0066.jpg'},
  {id:'blueberry-face',name:'Blueberry Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'Gentle, fresh and glow-focused face wash.',image:'assets/products/IMG-20260817-WA0067.jpg'},
  {id:'alpha-arbutin',name:'Alpha Arbutin Glow Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'Brightening and refreshing formula for everyday cleansing.',image:'assets/products/IMG-20260817-WA0068.jpg'},
  {id:'vitamin-c',name:'Vitamin C Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'Cleanse, purify and refresh with the Vitamin C Face Wash.',image:'assets/products/IMG-20260817-WA0069.jpg'},
  {id:'anti-acne',name:'Anti Acne Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'Face wash with tea tree oil and salicylic acid.',image:'assets/products/IMG-20260817-WA0070.jpg'},
  {id:'lemon',name:'Lemon Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'Refreshing, purifying and brightening face wash.',image:'assets/products/IMG-20260817-WA0071.jpg'},
  {id:'rose-petal',name:'Rose Petal Face Wash',price:'Rs. 1,050 (150ml)',category:'Face Wash',description:'Soft, soothing and brightening face wash.',image:'assets/products/IMG-20260817-WA0072.jpg'},
  {id:'white-prestige',name:'White Prestige 4D Serum',price:'Rs. 1,850 (70ml)',category:'Serums',description:'Non-greasy, lightweight serum formula.',image:'assets/products/IMG-20260817-WA0073.jpg'},
  {id:'glow-cream',name:'Glow Hydrating Cream',price:'50g - Rs. 750 · 100g - Rs. 1,000',category:'Creams',description:'Refreshing, soft and effective hydrating cream.',image:'assets/products/IMG-20260817-WA0074.jpg'},
  {id:'advanced-cream',name:'Advanced Brightening Cream',price:'50g - Rs. 750 · 100g - Rs. 1,000',category:'Creams',description:'Advanced brightening cream with lycopene and herbal extracts.',image:'assets/products/IMG-20260817-WA0075.jpg'},
  {id:'anti-aging',name:'Advance Skin Anti Aging Cream',price:'100g - Rs. 1,000 · 250g - Rs. 1,500',category:'Creams',description:'Advance Skin Anti Aging Cream by FJ Production.',image:'assets/products/IMG-20260817-WA0076.jpg'},
  {id:'hand-foot',name:'Hand & Foot Whitening Cream',price:'100g - Rs. 1,000',category:'Creams',description:'Hand and foot cream with niacinamide and herbal extract.',image:'assets/products/IMG-20260817-WA0077.jpg'},
  {id:'gold-gel',name:'24K Gold Gel',price:'100g - Rs. 750 · 350g - Rs. 1,500',category:'Other Skincare',description:'24K Gold Gel. Professional use only.',image:'assets/products/IMG-20260817-WA0046.jpg'},
  {id:'hair-oil',name:'FJ Hair Oil',price:'Rs. 1,000 (150ml)',category:'Hair Care',description:'FJ Hair Oil by FJ Production.',image:'assets/products/IMG-20260817-WA0047.jpg'},
  {id:'hair-mask',name:'Hair Protein Mask',price:'Rs. 1,500 (350g)',category:'Hair Care',description:'Hair Protein Mask with deep repair, smooth and shine.',image:'assets/products/IMG-20260817-WA0048.jpg'},
  {id:'blueberry-body',name:'Blueberry Body Wash',price:'Rs. 1,500 (350ml)',category:'Body Care',description:'Blueberry Body Wash by FJ Production.',image:'assets/products/IMG-20260817-WA0049.jpg'},
  {id:'strawberry-lip',name:'Strawberry Lip Balm',price:'Rs. 500 (25g)',category:'Other Skincare',description:'Strawberry tinted lip balm.',image:'assets/products/IMG-20260817-WA0050.jpg'},
  {id:'mint-kit',name:'Mint Facial Kit (10 Products)',price:'Small 350g - Rs. 10,000 · Large 500g - Rs. 13,000',category:'Facial Kits',description:'Mint facial kit with 10 products.',image:'assets/products/IMG-20260817-WA0051.jpg'},
  {id:'lavender-kit',name:'Lavender Facial Kit (10 Products)',price:'Small 350g - Rs. 10,000 · Large 500g - Rs. 13,000',category:'Facial Kits',description:'Lavender facial kit with 10 products.',image:'assets/products/IMG-20260817-WA0052.jpg'},
  {id:'strawberry-kit',name:'Strawberry Facial Kit (10 Products)',price:'Small 350g - Rs. 10,000 · Large 500g - Rs. 13,000',category:'Facial Kits',description:'Strawberry facial kit with 10 products.',image:'assets/products/IMG-20260817-WA0053.jpg'},
  {id:'lemon-vitamin',name:'Lemon & Vitamin C Face Wash',price:'Rs. 1,050 each (150ml)',category:'Face Wash',description:'Lemon and Vitamin C face wash.',image:'assets/products/IMG-20260817-WA0054.jpg'},
  {id:'blueberry-ice-aqua',name:'Blueberry · Ice Cool · Aqua Glow Face Wash',price:'Rs. 1,050 each (150ml)',category:'Face Wash',description:'Blueberry, Ice Cool and Aqua Glow face washes.',image:'assets/products/IMG-20260817-WA0055.jpg'},
  {id:'anti-acne-aloe',name:'Anti Acne & Aloe Vera Face Wash',price:'Rs. 1,050 each (150ml)',category:'Face Wash',description:'Anti Acne and Aloe Vera face washes.',image:'assets/products/IMG-20260817-WA0056.jpg'}
];

const grid=document.querySelector('#productGrid'),search=document.querySelector('#search'),category=document.querySelector('#categoryFilter'),price=document.querySelector('#priceFilter'),filterToggle=document.querySelector('#filterToggle');
function whatsappUrl(p,quantity=1){return `https://wa.me/923334105708?text=${encodeURIComponent(`Hello FJ Production, I would like to order:\n\nProduct: ${p.name}\nPrice: ${p.price}\nQuantity: ${quantity}\n\nPlease confirm my order.`)}`}
function render(items=products){grid.innerHTML=items.map((p,i)=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="${i>2?'lazy':'eager'}" onerror="this.classList.add('image-missing')"><span>${p.category}</span></div><div class="product-info"><div><h3>${p.name}</h3><b>${p.price}</b></div><p>${p.description}</p><div class="product-actions"><button class="details" data-id="${p.id}">View details</button><a class="order-mini" href="${whatsappUrl(p)}" target="_blank" rel="noopener">Order on WhatsApp ↗</a></div></div></article>`).join('')}
function filterProducts(){const q=search.value.toLowerCase().trim(),c=category.value,b=price.value;render(products.filter(p=>{const n=`${p.name} ${p.description} ${p.category}`.toLowerCase(),v=Number(String(p.price).replace(/[^0-9.]/g,''));return n.includes(q)&&(c==='all'||p.category===c)&&(b==='all'||b==='under-1000'&&v<1000||b==='1000-3000'&&v>=1000&&v<=3000||b==='over-3000'&&v>3000)}))}
[search,category,price].forEach(e=>e.addEventListener('input',filterProducts));filterToggle.addEventListener('click',()=>document.querySelector('#filters').classList.toggle('open'));
[...new Set(products.map(p=>p.category))].forEach(c=>category.insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));
const menu=document.querySelector('.mobile-nav');document.querySelector('.menu-toggle').addEventListener('click',e=>{const open=menu.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));render();
